# Site settings
title: "0o176 - in work..."
tagline: "None"
url: "https://0o176.github.io" # The base hostname & protocol for your site. Use it if you need absolute URL's

# Social
socialimg: /img/social.jpg # be sure to change this image
facebook: fbusername
twitter: twusername
github: ghusername
googleplus: gusername
instagram: igusername

# Contact
phone: "123-456-789" # This is my real number. You should text me.
email: "hello@garrettboatman.com" # This is my real email address. Please don't email me.


plugins:
  - jekyll-feed
  - jekyll-seo-tag

exclude: [.scss, README.md, node_modules, gruntfile.js, package.json]

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  parse_block_html: true
